language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
#addons:
#  sonarcloud:
#    organization: "avryhof-travis"
script:
#  - sonar-scanner
  - coverage run test.py
branches:
  only:
    - master
install:
  - pip install codecov
after_success:
- codecov
